kind: pipeline
type: docker
name: default

steps:
- name: gosec
  image: securego/gosec
  volumes:
  - name: gosec_vol
    path: /go
  commands:
  - gosec .

- name: build
  image: golang
  volumes:
  - name: gosec_vol
    path: /go
  commands:
  - go build wiki.go

volumes:
- name: gosec_vol
  temp: {}